const tones=[
 {id:1,title:'Little Wing',artist:'Jimi Hendrix',genre:'Blues',verified:true,source:'Rig Rundown · 3',amp:'Fender Bassman 100',chain:['Fuzz Face','Uni-Vibe','Vox Wah'],settings:{gain:62,bass:48,mids:66,treble:58,delay:18,reverb:34}},
 {id:2,title:'Back in Black',artist:'AC/DC',genre:'Rock',verified:true,source:'厂商资料 · 4',amp:'Marshall 1959 Plexi',chain:['无线系统','Marshall 4×12'],settings:{gain:74,bass:55,mids:72,treble:68,delay:5,reverb:12}},
 {id:3,title:'Do I Wanna Know?',artist:'Arctic Monkeys',genre:'Alternative',verified:false,source:'访谈推导 · 2',amp:'Vox AC30',chain:['Fuzz Factory','Analog Delay','Plate Reverb'],settings:{gain:68,bass:58,mids:44,treble:52,delay:32,reverb:48}},
 {id:4,title:'Sultans of Swing',artist:'Dire Straits',genre:'Rock',verified:true,source:'Rig Rundown · 5',amp:'Fender Vibrolux',chain:['Compressor','Overdrive','Digital Delay'],settings:{gain:34,bass:45,mids:61,treble:74,delay:28,reverb:25}},
 {id:5,title:'The Thrill Is Gone',artist:'B.B. King',genre:'Blues',verified:true,source:'访谈资料 · 3',amp:'Lab Series L5',chain:['轻微过载','Spring Reverb'],settings:{gain:29,bass:51,mids:70,treble:61,delay:8,reverb:41}},
 {id:6,title:'Everlong',artist:'Foo Fighters',genre:'Alternative',verified:false,source:'听感推导 · 1',amp:'Mesa/Boogie Dual Rectifier',chain:['Boss DS-1','Noise Gate','Room Reverb'],settings:{gain:82,bass:63,mids:38,treble:65,delay:6,reverb:19}}
];
let selectedTone=tones[0], activeGenre='全部';
const $=s=>document.querySelector(s);
function renderWave(){const w=$('#heroWave'); for(let i=0;i<58;i++){const b=document.createElement('i');b.style.height=`${18+Math.abs(Math.sin(i*.61))*72+Math.random()*22}px`;w.append(b)}}
function renderTones(){const q=$('#searchInput').value.toLowerCase();const verified=$('#verifiedOnly').checked;const list=tones.filter(t=>(activeGenre==='全部'||t.genre===activeGenre)&&(!verified||t.verified)&&`${t.title} ${t.artist} ${t.amp}`.toLowerCase().includes(q));$('#resultCount').textContent=`${list.length} 个公开样本`;$('#toneList').innerHTML=list.map(t=>`<article class="tone-card ${t.id===selectedTone.id?'selected':''}" data-id="${t.id}"><div class="tone-meta"><span>${t.genre}</span><b>${t.verified?'已验证':'推导'}</b></div><h3>${t.title}</h3><p>${t.artist} · ${t.amp}</p><div class="tone-meta" style="margin-top:18px"><span>${t.source}</span><span>→</span></div></article>`).join('');document.querySelectorAll('.tone-card').forEach(c=>c.onclick=()=>{selectedTone=tones.find(t=>t.id==c.dataset.id);renderTones();renderSelected()})}
function renderSelected(){$('#selectedTone').innerHTML=`<div class="rig-name">${selectedTone.title}</div><div class="rig-sub">${selectedTone.artist} · ${selectedTone.amp}</div>`;$('#signalChain').innerHTML=selectedTone.chain.map((x,i)=>`${i?'<b>→</b>':''}<span>${x}</span>`).join('')}
function adapt(){const amp=$('#ampSelect').value;const pedal=$('#pedalSelect').value;const shift=amp.includes('Marshall')?8:amp.includes('Vox')?-5:0;const s=selectedTone.settings;const rows=[['Gain',Math.max(0,Math.min(100,s.gain+shift))],['Bass',s.bass],['Mids',Math.max(0,Math.min(100,s.mids+(pedal.includes('TS9')?6:0)))],['Treble',s.treble],['Delay',s.delay],['Reverb',s.reverb]];$('#adaptationResult').innerHTML=`<div class="panel-title"><span>为 ${amp} 生成的设置</span><span class="confidence">匹配度 86%</span></div><div class="result-content"><div>${rows.slice(0,3).map(r=>`<div class="setting-row"><label>${r[0]}</label><input type="range" value="${r[1]}"/><span class="setting-value">${r[1]}</span></div>`).join('')}</div><div>${rows.slice(3).map(r=>`<div class="setting-row"><label>${r[0]}</label><input type="range" value="${r[1]}"/><span class="setting-value">${r[1]}</span></div>`).join('')}</div></div><p class="small-note">基于公开 Rig 和你的设备参数推导。先以耳朵为准，再微调 5–10%。</p>`;document.querySelectorAll('.setting-row input').forEach(i=>i.oninput=()=>i.nextElementSibling.textContent=i.value)}
let audioCtx,analyser,source,raf;
function makeSpectrum(){const s=$('#spectrum');s.innerHTML='';for(let i=0;i<64;i++){const b=document.createElement('i');b.style.height='2px';s.append(b)}}
async function toggleMic(){if(audioCtx){audioCtx.close();audioCtx=null;cancelAnimationFrame(raf);$('#micButton').innerHTML='◉ 开始监听';$('#micStatus').textContent='监听已停止';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioCtx=new AudioContext();analyser=audioCtx.createAnalyser();analyser.fftSize=128;source=audioCtx.createMediaStreamSource(stream);source.connect(analyser);$('#micButton').innerHTML='■ 停止监听';$('#micStatus').textContent='正在监听 · 仅本地处理';drawAudio()}catch(e){$('#micStatus').textContent='无法访问麦克风，请检查浏览器权限'}}
function drawAudio(){const data=new Uint8Array(analyser.frequencyBinCount);const time=new Uint8Array(analyser.fftSize);analyser.getByteFrequencyData(data);analyser.getByteTimeDomainData(time);let sum=0;time.forEach(v=>sum+=(v-128)**2);const rms=Math.sqrt(sum/time.length)/128;const pct=Math.min(100,Math.round(rms*180));$('#levelFill').style.width=`${pct}%`;$('#inputBar').style.width=`${pct}%`;$('#inputPercent').textContent=`${pct}%`;$('#levelValue').textContent=pct?`${Math.round(20*Math.log10(rms))} dB`:'-∞ dB';document.querySelectorAll('#spectrum i').forEach((b,i)=>b.style.height=`${Math.max(2,data[i]||0)/2}px`);$('#liveTip').innerHTML=pct<12?'<span>↗</span><div><strong>输入偏低</strong><p>靠近麦克风一点，或提高音频接口增益。</p></div>':pct>78?'<span>!</span><div><strong>注意削波</strong><p>把输入增益降低一些，保留动态空间。</p></div>':'<span>✦</span><div><strong>电平合适</strong><p>保持这个输入范围，开始比较目标音色。</p></div>';raf=requestAnimationFrame(drawAudio)}
document.addEventListener('DOMContentLoaded',()=>{renderWave();makeSpectrum();renderTones();renderSelected();document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');activeGenre=c.dataset.genre;renderTones()});$('#searchInput').oninput=renderTones;$('#verifiedOnly').onchange=renderTones;$('#adaptButton').onclick=adapt;$('#micButton').onclick=toggleMic;$('#resetGear').onclick=()=>{$('#guitarSelect').selectedIndex=0;$('#ampSelect').selectedIndex=0;$('#pedalSelect').selectedIndex=0};$('#themeButton').onclick=()=>document.body.classList.toggle('light')});
